### PR TITLE
[Performance] Drastically increase page load execution time

### PR DESCRIPTION
**Pull request by jabezborja**
# This PR improves the speed of execution of Brython.

The current implementation is bloating a PyFyre project. With just texts and anchors, a PyFyre project loads very slowly. The reason for this was that all of the Python and CPython modules were imported into a PyFyre project even if they weren't needed, such as `sys` and heck even the `os` module. The solution is that, instead of importing all of the Python and CPython modules, the project will just cherry-pick a module that is only used in the project.

## Benchmark
image
`brython_stdlib.js` - What Brython executes in just-in-time execution, about 4,484 KB with all of Typing, Asyncio, etc. modules.
`modules.js` - Cherry-picked modules in the project BUT without Typing, Sys, Traceback, and Asyncio (With Typing it's about 2,913 KB) 
`With all of modules` - Approx. **4000ms** before the DOM loads
`Without and cherry-picked` - Approx. **600ms** before the DOM loads

**_Does this have any breaking API changes?_ Only `on_build_error` function in `base.py`**

**Downside**:
- Removed modules such as Typing, Asyncio (aio), Traceback, and Sys (not necessarily but removing this will showcase the changes boldly)

## Other changes
Instead of using the `public/` folder to run the app, PyFyre will just create a temporary folder called `_pyfyre` in the main directory and host the application there. `_pyfyre` folder should be ignored in `.gitignore`

### CODE REVIEW

**Comment by NadieFiind** [comment]
I have another concern in addition to what we have discussed on Discord.

In your implementation, you are only executing `brython-cli make_modules` in the PyFyre files, but not in the user files. This can be a problem when a user used a standard library that isn't included in the cherry-picked modules.

My solution was to just include the user files when executing `brython-cli make_modules`. But then another problem has arisen. Executing `brython-cli make_modules` is very slow. That will make the development of the user even slower because every time the app rebuilds when a user made a change, it will have to execute `brython-cli make_modules` over and over again. Which is really bad.

My solution to that problem is to just not use `brython-cli make_modules`. **Except** when the user runs `pyfyre build`. This will make development with PyFyre faster.

So when the user runs `pyfyre run`, the app will use the CDN of Brython standard lib. And when the user runs `pyfyre build`, PyFyre will execute `brython-cli make_modules` to cherry-pick the only used modules.

**Comment by jabezborja** [comment]
> My solution to that problem is to just not use `brython-cli make_modules`. Except when the user runs `pyfyre build`. This will make development with PyFyre faster.

If we're going to do that, we have to put the whole PyFyre module to the user's directory. Using that built-in virtual file system by Brython, we don't have to do that.

**Comment by NadieFiind** [comment]
I am not saying that we will remove the virtual file system by Brython. Instead, only use it when the user runs `pyfyre build`. In `pyfyre run`, we should not execute `brython-cli make_modules` because it is very slow. Instead, let us just use `brython-cli make_package` to bundle the `src` and pyfyre files together.

**Comment by NadieFiind** [comment]
The changes on this branch are now stable to be merged with the target branch. Merging this branch now. @jabezborja if you have more concerns, let us discuss it on Discord, and feel free to make another pull request.

**Pull request merged**
